class SourceCardsController < ApplicationController

  hobo_model_controller

  # Source cards are generated by processing flux spectra files,
  # so we don't need the index, new and create actions.
  auto_actions :all, :except => [ :index, :new, :create ]

end
